<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0-windows;net10.0</TargetFrameworks>
    <TargetFramework Condition="'$(TargetFramework)' == '' and $([MSBuild]::IsOSPlatform('Windows'))">net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot Condition="'$(TargetFramework)' == 'net10.0-windows'">true</PublishAot>
    <BuiltInComInteropSupport Condition="'$(TargetFramework)' == 'net10.0-windows'">true</BuiltInComInteropSupport>
    <InvariantGlobalization Condition="'$(TargetFramework)' == 'net10.0-windows'">true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\xidio.Core\xidio.Core.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
    <ProjectReference Include="..\xidio.Platform.Windows\xidio.Platform.Windows.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0' and $([MSBuild]::IsOSPlatform('Linux'))">
    <DefineConstants>$(DefineConstants);LINUX</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0' and $([MSBuild]::IsOSPlatform('OSX'))">
    <DefineConstants>$(DefineConstants);MACOS</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0' and $([MSBuild]::IsOSPlatform('Linux'))">
    <ProjectReference Include="..\xidio.Platform.Linux\xidio.Platform.Linux.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0' and $([MSBuild]::IsOSPlatform('OSX'))">
    <ProjectReference Include="..\xidio.Platform.macOS\xidio.Platform.macOS.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.55.2" />
  </ItemGroup>

</Project>
